const HTTP_STATUS_OK = 200
const HTTP_STATUS_CREATED = 201
const HTTP_STATUS_NO_CONTENT = 204
const HTTP_STATUS_VALIDATION_ERROR = 400
const HTTP_STATUS_NOT_FOUND = 404
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

const ERROR_TYPE_VALIDATION_ERROR = 'ValidationError'
const ERROR_TYPE_NOTFOUND_ERROR = 'NotFoundError'
const ERROR_TYPE_GATEWAY_ERROR = 'GatewayError'

const ERROR_MSG_INTERNAL_SERVER_ERROR = 'Internal server error'
const ERROR_MSG_NOT_FOUND = `could not be found`

const GATEWAY_STATUS_ONLINE = 'online'
const GATEWAY_STATUS_OFFLINE = 'offline'

module.exports = {
    HTTP_STATUS_OK,
    HTTP_STATUS_CREATED,
    HTTP_STATUS_NO_CONTENT,
    HTTP_STATUS_VALIDATION_ERROR,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_INTERNAL_SERVER_ERROR,
    ERROR_TYPE_VALIDATION_ERROR,
    ERROR_TYPE_NOTFOUND_ERROR,
    ERROR_TYPE_GATEWAY_ERROR,
    ERROR_MSG_INTERNAL_SERVER_ERROR,
    ERROR_MSG_NOT_FOUND,
    GATEWAY_STATUS_ONLINE,
    GATEWAY_STATUS_OFFLINE
}